### ISSUE TITLE
Post example do not work

### ISSUE THREAD

**Issue by kimras** [mipsweb/quickpayexample#1]
I have big problems getting the Checksum working from the sample you posted.. the Callback works fine, but the Post produces a Invalid Checksum error..
Can you share the CSHTML file or help indicate what to look for.
thanks in advance

**Comment by mipsweb** [comment]
I have the same problems in the beginning. The problem was that I had more input forms than in the example http://tech.quickpay.net/payments/hosted/. You may only have the same input elements as shown in the example.
ASP.NET Webforms many give some problems because of the auto-generated hidden forms elements (__EVENTTARGET, __EVENTARGUMENT, __VIEWSTATE).

Hope you can use the answer.

**Comment by kimras** [comment]
Thanks from your rapid reply.. It totally make sence.. But I build the POS my self like this:
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
    <body>
        <div>
           Status: @ViewBag.Status

            @if (ViewBag.Status == "Ok")
            {
                <form method="POST" action="https://payment.quickpay.net">
                    <input type="hidden" name="version" value="v10">
                    <input type="hidden" name="merchant_id" value="@ViewBag.MerchantId">
                    <input type="hidden" name="agreement_id" value="@ViewBag.AgreementId">
                    <input type="hidden" name="order_id" value="@ViewBag.OrderId">
                    <input type="hidden" name="amount" value="@ViewBag.Amount">
                    <input type="hidden" name="currency" value="@ViewBag.Currency">
                    <input type="hidden" name="autofee" value="@ViewBag.Autofee">
                    <input type="hidden" name="autocapture" value="@ViewBag.Autocapture">

                    <input type="hidden" name="continueurl" value="@ViewBag.ContinueUrl">
                    <input type="hidden" name="cancelurl" value="@ViewBag.CancelUrl">
                    <input type="hidden" name="callbackurl" value="@ViewBag.CallbackUrl">

                    <input type="hidden" name="checksum" value="@ViewBag.Checksum">

                    <input type="submit" value="Continue to payment...">
                </form>
            }
        </div>
    </body>
</html>

Can you see any obvious ? or maybe share your View that is called from your Post code ?
Thanks

**Comment by mipsweb** [comment]
I can't see any obvious. It looks like my code. You are taking Merchant Id, Agreement, etc. for the Payment Window?

**Comment by kimras** [comment]
Ok, I found the issue, the calculation had a Language the View did not.. I guess I could build something dynamic to calculate Checksum and build Post from so it cannot be out of sync..
Thanks for your assistance.
